In [1]:
import os
import numpy as np
import pandas as pd
from tqdm import tqdm_notebook as tqdm
print(os.listdir("../input"))
np.random.seed(42)

['ey-nextwave', 'ndscindexes', 'eyn-pre-unravel-df', 'eyn-original']


In [2]:
train_targets_inside = np.load("../input/eyn-original/train_targets_inside.npy")
df_train = pd.read_pickle("../input/eyn-pre-unravel-df/df_train.pickle")
df_test = pd.read_pickle("../input/eyn-pre-unravel-df/df_test.pickle")
print(df_train.shape, df_test.shape)
df_train

(2815323, 23) (703815, 23)


t_entry    t_exit    ...      dir_x_a   dir_y_a
seq    traj                        ...                       
0      0     0.004194  0.030917    ...     0.094538  0.995521
       1    -0.036417 -0.036417    ...     0.200257  0.979743
       2    -0.670278 -0.637694    ...     0.760436  0.649413
       3    -0.710778 -0.694306    ...    -0.040913  0.999163
       4    -0.765722 -0.757167    ...    -0.324647 -0.945835
       5    -0.792472 -0.785778    ...          NaN       NaN
       6          NaN       NaN    ...          NaN       NaN
       7          NaN       NaN    ...          NaN       NaN
       8          NaN       NaN    ...          NaN       NaN
       9          NaN       NaN    ...          NaN       NaN
       10         NaN       NaN    ...          NaN       NaN
       11         NaN       NaN    ...          NaN       NaN
       12         NaN       NaN    ...          NaN       NaN
       13         NaN       NaN    ...          NaN       NaN
       14         NaN       NaN    ...          NaN       NaN
       15         NaN       NaN    ...          NaN       NaN
       16         NaN       NaN    ...          NaN       NaN
       17         NaN       NaN    ...          NaN       NaN
       18         NaN       NaN    ...          NaN       NaN
       19         NaN       NaN    ...          NaN       NaN
       20         NaN       NaN    ...          NaN       NaN
1      0     0.000889  0.049667    ...     0.856899  0.515484
       1    -0.016278 -0.016278    ...    -0.454480  0.890757
       2    -0.033639 -0.033639    ...    -0.852162 -0.523278
       3    -0.051028 -0.051028    ...          NaN       NaN
       4          NaN       NaN    ...          NaN       NaN
       5          NaN       NaN    ...          NaN       NaN
       6          NaN       NaN    ...          NaN       NaN
       7          NaN       NaN    ...          NaN       NaN
       8          NaN       NaN    ...          NaN       NaN
...               ...       ...    ...          ...       ...
134061 12         NaN       NaN    ...          NaN       NaN
       13         NaN       NaN    ...          NaN       NaN
       14         NaN       NaN    ...          NaN       NaN
       15         NaN       NaN    ...          NaN       NaN
       16         NaN       NaN    ...          NaN       NaN
       17         NaN       NaN    ...          NaN       NaN
       18         NaN       NaN    ...          NaN       NaN
       19         NaN       NaN    ...          NaN       NaN
       20         NaN       NaN    ...          NaN       NaN
134062 0    -0.005389  0.006806    ...     0.473617  0.880731
       1    -0.065944 -0.054583    ...    -0.732063 -0.681237
       2    -0.512972 -0.512972    ...    -0.710176 -0.704024
       3    -0.896194 -0.896194    ...     0.710176  0.704024
       4    -1.264694 -1.264694    ...    -0.710176 -0.704024
       5    -1.296194 -1.296194    ...    -0.627121 -0.778922
       6    -1.474278 -1.474278    ...          NaN       NaN
       7          NaN       NaN    ...          NaN       NaN
       8          NaN       NaN    ...          NaN       NaN
       9          NaN       NaN    ...          NaN       NaN
       10         NaN       NaN    ...          NaN       NaN
       11         NaN       NaN    ...          NaN       NaN
       12         NaN       NaN    ...          NaN       NaN
       13         NaN       NaN    ...          NaN       NaN
       14         NaN       NaN    ...          NaN       NaN
       15         NaN       NaN    ...          NaN       NaN
       16         NaN       NaN    ...          NaN       NaN
       17         NaN       NaN    ...          NaN       NaN
       18         NaN       NaN    ...          NaN       NaN
       19         NaN       NaN    ...          NaN       NaN
       20         NaN       NaN    ...          NaN       NaN

[2815323 rows x 23 columns]

In [3]:
df_train_values = df_train.values
df_test_values = df_test.values
df_train_columns = df_train.columns
df_test_columns = df_test.columns

### original 4 folds

In [4]:
# standardised 4-fold train-test split for clustering purposes
from sklearn.model_selection import StratifiedKFold, KFold
skf = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)
trn_index_list = []
val_index_list = []
for trn_index, val_index in skf.split(np.arange(len(df_train_values[::21])),
                                      train_targets_inside.astype(int)):
    trn_index_list.append(trn_index)
    val_index_list.append(val_index)
    
np.save("trn_index_list",trn_index_list)
np.save("val_index_list",val_index_list)

### 10 folds

In [5]:
from sklearn.model_selection import StratifiedKFold, KFold
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
trn_index_list = []
val_index_list = []
for trn_index, val_index in skf.split(np.arange(len(df_train_values[::21])),
                                      train_targets_inside.astype(int)):
    trn_index_list.append(trn_index)
    val_index_list.append(val_index)
    
np.save("trn_index_list_10f",trn_index_list)
np.save("val_index_list_10f",val_index_list)

### 15 folds

In [6]:
from sklearn.model_selection import StratifiedKFold, KFold
skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
trn_index_list = []
val_index_list = []
for trn_index, val_index in skf.split(np.arange(len(df_train_values[::21])),
                                      train_targets_inside.astype(int)):
    trn_index_list.append(trn_index)
    val_index_list.append(val_index)
    
np.save("trn_index_list_15f",trn_index_list)
np.save("val_index_list_15f",val_index_list)

## Inside and stationary indexes

In [7]:
train_last_is_stationary = np.argwhere(df_train_values[::21,df_train_columns.get_loc("dur")] == 0)[:,0]
train_last_not_stationary = np.argwhere(df_train_values[::21,df_train_columns.get_loc("dur")] != 0)[:,0]
test_last_is_stationary = np.argwhere(df_test_values[::21,df_test_columns.get_loc("dur")] == 0)[:,0]
test_last_not_stationary = np.argwhere(df_test_values[::21,df_test_columns.get_loc("dur")] != 0)[:,0]
print(train_last_is_stationary.shape, train_last_not_stationary.shape)
print(test_last_is_stationary.shape, test_last_not_stationary.shape)

train_last_seen_is_inside = np.argwhere(df_train_values[::21,df_train_columns.get_loc("entry_in")] == 1)[:,0]
train_last_seen_not_inside = np.argwhere(df_train_values[::21,df_train_columns.get_loc("entry_in")] == 0)[:,0]
test_last_seen_is_inside = np.argwhere(df_test_values[::21,df_test_columns.get_loc("entry_in")] == 1)[:,0]
test_last_seen_not_inside = np.argwhere(df_test_values[::21,df_test_columns.get_loc("entry_in")] == 0)[:,0]
print(train_last_seen_is_inside.shape, train_last_seen_not_inside.shape)
print(test_last_seen_is_inside.shape, test_last_seen_not_inside.shape)

np.save("train_last_is_stationary", train_last_is_stationary)
np.save("train_last_not_stationary", train_last_not_stationary)
np.save("test_last_is_stationary", test_last_is_stationary)
np.save("test_last_not_stationary", test_last_not_stationary)
np.save("train_last_seen_is_inside", train_last_seen_is_inside)
np.save("train_last_seen_not_inside", train_last_seen_not_inside)
np.save("test_last_seen_is_inside", test_last_seen_is_inside)
np.save("test_last_seen_not_inside", test_last_seen_not_inside)

last_nonstat_indexes = train_last_not_stationary

(66998,) (67065,)
(16841,) (16674,)
(38449,) (95614,)
(9544,) (23971,)


## Other number of folds

Now we exclude points that end up to be stationary

### 10 folds unreserved stationary-excluded
without reserve for ensembling

In [8]:
from sklearn.model_selection import StratifiedKFold, KFold
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
trn_index_list = []
val_index_list = []
for trn_index, val_index in skf.split(np.arange(len(df_train_values[::21])), train_targets_inside.astype(int)):
    trn_index = np.intersect1d(trn_index, last_nonstat_indexes)
    val_index = np.intersect1d(val_index, last_nonstat_indexes)
    trn_index_list.append(trn_index)
    val_index_list.append(val_index)
print(trn_index.shape, val_index.shape)
print(trn_index, val_index)

np.save("trn_index_list_10f_nostat",trn_index_list)
np.save("val_index_list_10f_nostat",val_index_list)

(60355,) (6710,)
[     0      1      2 ... 134058 134059 134062] [    37     75     84 ... 134035 134038 134046]


### 15 folds unreserved 

In [9]:
from sklearn.model_selection import StratifiedKFold, KFold
skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
trn_index_list = []
val_index_list = []
for trn_index, val_index in skf.split(np.arange(len(df_train_values[::21])), train_targets_inside.astype(int)):
    trn_index = np.intersect1d(trn_index, last_nonstat_indexes)
    val_index = np.intersect1d(val_index, last_nonstat_indexes)
    trn_index_list.append(trn_index)
    val_index_list.append(val_index)
print(trn_index.shape, val_index.shape)
print(trn_index, val_index)

np.save("trn_index_list_15f_nostat",trn_index_list)
np.save("val_index_list_15f_nostat",val_index_list)

(62588,) (4477,)
[     0      1      2 ... 134058 134059 134062] [    75     84    156 ... 133999 134035 134038]


## Now with reserve for emsemble



In [10]:
np.random.shuffle(last_nonstat_indexes)

trn_val_index, ems_index = np.split(last_nonstat_indexes, [int(.9*len(last_nonstat_indexes))])
trn_val_index = np.sort(trn_val_index)
ems_index = np.sort(ems_index)
print(ems_index.shape, trn_val_index.shape)

(6707,) (60358,)


### 10 folds reserved

In [11]:
from sklearn.model_selection import StratifiedKFold, KFold
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
trn_index_list = []
val_index_list = []
for trn_index, val_index in skf.split(np.arange(len(df_train_values[::21])), train_targets_inside.astype(int)):
    trn_index = np.intersect1d(np.intersect1d(trn_index, last_nonstat_indexes), trn_val_index)
    val_index = np.intersect1d(np.intersect1d(val_index, last_nonstat_indexes), trn_val_index)
    trn_index_list.append(trn_index)
    val_index_list.append(val_index)
print(trn_index.shape, val_index.shape, ems_index.shape)
print(trn_index, val_index)
    
np.save("trn_index_list_e10_10f_nostat",trn_index_list)
np.save("val_index_list_e10_10f_nostat",val_index_list)
np.save("ems_index_e10_nostat",ems_index)

(54320,) (6038,) (6707,)
[     0      1      2 ... 134058 134059 134062] [    37     75     84 ... 134035 134038 134046]


In [12]:
!ls

__notebook__.ipynb		trn_index_list_10f.npy
__output__.json			trn_index_list_10f_nostat.npy
ems_index_e10_nostat.npy	trn_index_list_15f.npy
test_last_is_stationary.npy	trn_index_list_15f_nostat.npy
test_last_not_stationary.npy	trn_index_list_e10_10f_nostat.npy
test_last_seen_is_inside.npy	val_index_list.npy
test_last_seen_not_inside.npy	val_index_list_10f.npy
train_last_is_stationary.npy	val_index_list_10f_nostat.npy
train_last_not_stationary.npy	val_index_list_15f.npy
train_last_seen_is_inside.npy	val_index_list_15f_nostat.npy
train_last_seen_not_inside.npy	val_index_list_e10_10f_nostat.npy
trn_index_list.npy
